BlackJack/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:productid>/', views.product, name='productpage')
    ]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('addcoupon/', views.addcoupon, name='addcoupon'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('deactivatecoupon/<str:couponcode>', views.deactivatecoupon, name='deactivatecoupon'),
    path('editproduct/<str:productid>/', views.editproduct, name='editproduct'),
    path('',views.dashboard,name='shopdashboard'),
    path('<str:shopname>/', views.index, name='shop'),
    path('activecoupons/', views.activecoupons,name='activecoupons'),
    path('orders/',views.orders,name='shop_orders'),
    path('remove/<str:productid>',views.removefromshop,name='removefromshop')
]

products/models.py
from django.db import models
import datetime
import uuid
# Create your models here.

class Review(models.Model):
    text = models.TextField()
    stars = models.DecimalField(max_digits=7,decimal_places=2)
    user = models.ForeignKey('users.User',on_delete=models.SET_NULL,null=True)
    date = models.DateTimeField(auto_now=True, blank=True)
    def __str__(self):
        return f'{self.text}'


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    description = models.TextField(blank=True)
    remaininginstock = models.PositiveSmallIntegerField(default=1)
    featured = models.BooleanField(default=False)
    image = models.ImageField(null=True,blank=True,upload_to='product_images/')
    shop = models.ForeignKey('shop.Shop',on_delete=models.CASCADE)
    reviews = models.ManyToManyField(Review, blank=True, related_name="reviews")
    categories = [
        ('clothing','Clothing'),
        ('tvs','TVs'),
        ('electronics','Electronics'),
        ('home_applicanes','Home Appliances'),
        ('furniture','Furniture'),
        ('other','Other')
    ]
    category_map={
        'clothing':'Clothing',
        'tvs':'TVs',
        'electronics':'Electronics',
        'home_appliances':'Home Appliances',
        'furniture':'Furniture',
        'other':'Other'
    }
    category = models.CharField(max_length=15,choices=categories,default='other')
    visits = models.IntegerField(default=0)
    def __str__(self):
        return f'{self.name}'
    def __unicode__(self):
        return self.id

products/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ValidationError
from .models import Product,Review
import requests 
import decimal
import random,os
from decouple import config
# Create your views here.
currency_symbols={
    'EGP':'EGP',
    'EUR':'€',
    'USD':'$',
    'GBP':'£'
}

currency_names={
    'EGP':'Egyptian Pound',
    'EUR':'Euro',
    'USD':'US Dollars',
    'GBP':'English Pounds'
}
def get_currency_ratio(request):
    preferred_currency=get_preffered_currency(request)
    if preferred_currency=='EGP':
        return 1
    else:
        return requests.get('https://free.currconv.com/api/v7/convert',{'apiKey':config('API_KEY'),'q':'EGP'+'_'+preferred_currency,'compact':'ultra'}).json()['EGP'+'_'+preferred_currency]

def get_preffered_currency(request):
    if not request.user.is_authenticated:
        return 'EGP'
    if request.user.preferred_currency=='':
        return 'EGP'
    return request.user.preferred_currency

    
def product(request, productid):
    if request.method=='POST':
        if 'add_review' in request.POST:
            text=request.POST.get('review','')
            rating=request.POST.get('rate',1)
            u = request.user
            rev=Review(text=text,stars=rating, user=u)
            rev.save()
            product=Product.objects.get(id=productid)
            product.reviews.add(rev)
            return HttpResponseRedirect(reverse('productpage',args=[productid]))

        elif 'add_to_cart' in request.POST:
            if request.user.is_authenticated:
                product_id = request.POST['productid']
                product = Product.objects.get(id=product_id)
                request.user.cart.add(product)

                return HttpResponseRedirect(reverse('productpage',args=[productid]))
            else:
                return HttpResponseRedirect(reverse('login'))
        elif 'add_to_wishlist' in request.POST:
            if request.user.is_authenticated:
                product_id = request.POST['productid']
                product = Product.objects.get(id=product_id)
                request.user.wishlist.add(product)

                return HttpResponseRedirect(reverse('productpage',args=[productid]))
            else:
                return HttpResponseRedirect(reverse('login'))
    else:
        try:
            product = Product.objects.get(id=productid)
            visits = product.visits
            if visits >= 99:
                product.featured = True
            product.visits = visits + 1
            product.save()
            r_products = list(Product.objects.filter(category=product.category))
            r_products.remove(product)
            featured = []
            related = []
            if len(r_products) <= 4:
                related = r_products
            else:
                for p in r_products:
                    if p.featured:
                        featured.append(p)
                if len(featured) == 4:
                    related = featured
                elif len(featured) < 4:
                    while len(featured) < 4:
                        random_product = random.choice(r_products)
                        if random_product not in featured:
                            featured.append(random_product)
                    related = featured
                else:
                    while len(related) < 4:
                        random_product = random.choice(featured)
                        if random_product not in related:
                            related.append(random_product)
            rating = 0
            reviews = product.reviews.all()
            for rev in reviews:
                rating += rev.stars
            if len(reviews) > 0:
                rating /= len(reviews)
            else:
                rating = 0
            if request.user.is_authenticated:
                in_wishlist=product in request.user.wishlist.all()
                in_cart=product in request.user.cart.all()
            else:
                in_wishlist=None
                in_cart=None
            is_user_product=False
            if request.user:
                if request.user.is_authenticated and request.user.shop:
                    if product.shop.id==request.user.shop.id:
                        is_user_product=True
            user_has_review=False
            if request.user.is_authenticated:
                if Review.objects.filter(user=request.user,reviews=product):
                    user_has_review=True
            request.session['Last_URL']=request.path
            return render(request,'products/product.html',{
            'product': product,
            'rating': rating,
            'currency_ratio': get_currency_ratio(request),
            'preferred_currency':get_preffered_currency(request),
            'currency_symbol':currency_symbols[get_preffered_currency(request)],
            'reviews':reviews,
            'in_wishlist':in_wishlist,
            'in_cart': in_cart,
            'is_user_product':is_user_product,
            'user_has_review':user_has_review,
            'related':related,
            'related_len':len(related),
            'currency_ratio':get_currency_ratio(request),
            'currency_name':currency_names[get_preffered_currency(request)]
            })
        except (Product.DoesNotExist,ValidationError) :
            return render(request,'products/404.html')
        
    
    

products/templates/products/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock%}</title> 
    {% block head %}{% endblock %}
</head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
        {% block script%}
        {% endblock %}
</html>

products/templates/products/product.html
{% extends 'products/layout.html' %}
{% load static %}
{% load mathfilters %}
{% block title%}{{ product.name }}{% endblock %}
{% block head %}
      <link rel="stylesheet" href="{% static 'products/styles.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block body%}
<header>
  <div class="Container">
      <div id="header">
        <span><a id="BlackJack" href="{% url 'home' %}">BlackJack</a></span>
        <span><a id="official" href="{% url 'home' %}">The Official online store</a> </span>
 </div>

<nav> <ul style="margin-top:12px;"> 
  {% if user.is_authenticated %}
    <li> <a href="{% url 'home' %}"> Home </a> </li>
    <li> <a href="{% url 'userdashboard' %}"> Profile </a></li>
    <li> <a href="{% url 'contactus' %}"> Contact Us </a></li>
    <li> <a href="{% url 'logout' %}">  Logout  </a> </li>
    {% else %}
    <li> <a href="{% url 'home' %}"> Home </a> </li>
    <li> <a href="{% url 'signup' %}">SignUp</a></li>
    <li> <a href="{% url 'login' %}">  Login  </a> </li>
    {% endif %}
</ul> </nav>
</header>
    <div class="product-container">
    <div class="product">
      <div class="info">
        <div class="info-text">
          <h1>{{ product.name }}</h1>
          <h2>Shop: <a class="shoplink" href="{% url 'shop' product.shop.name %}">{{product.shop.name}}</a> <h2>
          <h2>Price: {{ product.price|mul:currency_ratio|floatformat:2 }} {{currency_symbol}}</h2>
          <h2>Category: {{product.get_category_display}}</h2>
          <h2>Quantity: {{ product.remaininginstock }}</h2>
          <h2>Rating: {{ rating }}</h2>
        </div>
        <form action="{% url 'productpage' product.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="productid" value="{{ product.id }}">
          <button type="submit" name="add_to_wishlist" class="wishlist" 
          {% if in_wishlist or is_user_product%}
            disabled style="color:#ccc; cursor:default;"
          {% endif %}
          >
          <i class="fa fa-heart"></i> Add to wishlist</button>
        </form>
        <form action="{% url 'productpage' product.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="productid" value="{{ product.id }}">
          <button type="submit" name="add_to_cart" class="cart"
          {% if in_cart or product.remaininginstock == 0 or is_user_product %}
            disabled style="color:#ccc; cursor:default;"
          {% endif %}
          >
          <i class="fa fa-shopping-cart"></i> Add to Cart</button>
        </form>
      </div>
      <div class="image">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" id="productimage">
      </div>
    </div>
    {% if product.remaininginstock == 0 %}
      <div style="color:red; font-size: 1.5rem; text-align: center;">
          <br>
          Product is out of stock!
      </div>
    {% endif %}      
    </div>
<div class="Dis"  style="width: 97.5%;">
  <h6>Product Discription</h6>
  <p id="description">{{product.description}}</p>
</div>
<div class="Rev">
<form action="{% url 'productpage' product.id %}" method="POST">
  {% csrf_token %}
<h6>Write a Review</h6>
<textarea name="review" id="review_text" placeholder="Write your review here"></textarea>
<!-- <div class="rating"> <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label> <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label> <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label> <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label> <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
</div> -->
<div class="rate">
  <input type="radio" id="star5" name="rate" value="5" />
  <label for="star5" title="text">5 stars</label>
  <input type="radio" id="star4" name="rate" value="4" />
  <label for="star4" title="text">4 stars</label>
  <input type="radio" id="star3" name="rate" value="3" />
  <label for="star3" title="text">3 stars</label>
  <input type="radio" id="star2" name="rate" value="2" />
  <label for="star2" title="text">2 stars</label>
  <input type="radio" id="star1" name="rate" value="1" />
  <label for="star1" title="text">1 star</label>
</div>
<input type="submit" name="add_review" id="review_btn" class="review_btn" disabled>
</form>
</div>
<div class="user-reviews">
  <h6>User Reviews</h6>
  {% if reviews %}
  {% for review in reviews%}
    <div class="single-review">
    <p>By <em style="font-size: 1.1em;">{{ review.user.username }}</em></p>
    <img src="../../static/products/{{ review.stars|floatformat:0 }}.png" alt="{{ review.stars|floatformat:0 }}">
    <p>{{ review.text }}</p>
    </div>
  {% endfor %}
  {% else %}
    <p style="font-size: 1.5rem; text-align: center;">There are no reviews for this product.</p>
  {% endif %}
</div>

{% if related_len > 0 %}
<div class="Related">
  <h6>Related Products</h6>
  <div style="display:flex; justify-content:center">
  {% for p in related %}
  <div class="v">
    <img src="{{ p.image.url}}" alt="{{p.name}}" class="re">
    <h5><a class="p_name" href="{% url 'productpage' p.id %}">{{p.name}}</a></h5>
    <h5>{{p.price|mul:currency_ratio|floatformat:2}} {{currency_name}}</h5>
    <!-- <button type="submit" class="art">Add to Cart</button> -->
   </div>
   {% endfor %}
  </div>
  <!-- <div class="v">
    <img src="" class="re">
    <h5> Product Name</h5>
    <h5>price</h5>
    <button type="submit" class="art">Add to Cart</button>
   </div>
   <div class="v">
     <img src="" class="re">
     <h5> Product Name</h5>
     <h5>price</h5>
     <button type="submit" class="art">Add to Cart</button>
    </div>
    <div class="v">
      <img src="" class="re">
      <h5> Product Name</h5>
      <h5>price</h5>
      <button type="submit" class="art">Add to Cart</button>
     </div> -->
    </div>
{% endif %}

    {% if not is_user_product and not user_has_review%}
      <script>
        var review=document.getElementById('review_text');
        var submit=document.getElementById('review_btn');
        review.addEventListener('input',function (){
          console.log(review.value.length);
          if (review.value.length>30){
            submit.disabled=false;
          }
          else
            submit.disabled=true;
        })
      </script>
    {% endif %}
    {% endblock %}

  